Repository algosup/2024-2025-project-3-quickest-path-team-5, pull requests merged in 2025-02, with the labels that each got.

#23 PR - Functional specifications
  documents/functional_specifications/FunctionalSpecifications.md
  documents/functional_specifications/images/logo_quickest_path.png
  documents/functional_specifications/images/web_app.png
Labels: documentation

#28 A* landmarks corrected and optimized
  cap/CMakeLists.txt
  cap/src/cap.cpp
  cap/src/data_struct/edge.cpp
  cap/src/data_struct/edge.hpp
  cap/src/data_struct/graph.cpp
  cap/src/data_struct/graph.hpp
  cap/src/data_struct/node.cpp
  cap/src/data_struct/node.hpp
  dag_graph_validator/CMakeLists.txt
Labels: enhancement, code

#34 Sub functional specifications
  documents/Manual/Usermanual.pdf
  documents/Manual/images/destination.png
  documents/Manual/images/format.png
  documents/Manual/images/map2.jpg
  documents/Manual/images/results.png
  documents/Manual/images/submit.png
  documents/Manual/usermanual.md
  documents/functional_specifications/FunctionalSpecifications.md
Labels: documentation, enhancement

#35 PR- Functional specifications
  documents/functional_specifications/FunctionalSpecifications.md
  documents/functional_specifications/images/find_path.png
  documents/functional_specifications/images/format.png
  documents/functional_specifications/images/input.png
  documents/functional_specifications/images/research.png
  documents/functional_specifications/images/result.png
  documents/functional_specifications/images/web_app.png
Labels: documentation

#37 updating the project tree
  documents/technical_specifications/TechnicalSpecifications.md
Labels: documentation, enhancement

#39 Project management docs to merge
  documents/.gitignore
  documents/Management/ManagementArtifacts/code_of_conduct.md
  documents/Management/ManagementArtifacts/management_artifact.md
  documents/Management/ManagementArtifacts/project_charter.md
  documents/Management/weeklyReport.md/weekly_report_1.md
  documents/Management/weeklyReport.md/weekly_report_2.md
  documents/Management/weeklyReport.md/weekly_report_3.md
  documents/Management/weeklyReport.md/weekly_report_4.md
Labels: documentation

#38 Readme update
  README.md
  dag_graph_validator/src/data_struct/graph_lib.c
  dag_graph_validator/src/data_struct/graph_lib.h
Labels: documentation

#45 Unit tests improve
  cap/test/test.cc
Labels: enhancement, code

#53 issues
  documents/Management/CODE_OF_CONDUCT.md
  documents/Management/weeklyReport.md/weekly_report_1.md
Labels: documentation

#51 Documents
  documents/.gitignore
  documents/Management/CODE_OF_CONDUCT.md
  documents/Management/ManagementArtifacts/management_artifact.md
  documents/Management/ManagementArtifacts/project_charter.md
  documents/Management/weeklyReport.md/weekly_report_1.md
  documents/Management/weeklyReport.md/weekly_report_2.md
  documents/Management/weeklyReport.md/weekly_report_3.md
  documents/Management/weeklyReport.md/weekly_report_4.md
  documents/Management/weeklyReport.md/weekly_report_5.md
  documents/Manual/usermanual.pdf
  documents/technical_specifications/TechnicalSpecifications.md
Labels: documentation, enhancement

#52 Patch workflow
  .github/workflows/test-caller.yml
Labels: enhancement

#49 Update CAP definition in readme
  README.md
Labels: documentation

#54 cumulative document and links for the weekly report
  CODE_OF_CONDUCT.md
  documents/Management/ManagementArtifacts/management_artifact.md
  documents/Management/weeklyReport.md/cumulative.md
Labels: documentation

#55 Documents management + code of conduct to the main
  CODE_OF_CONDUCT.md
  documents/Management/ManagementArtifacts/management_artifact.md
  documents/Management/weeklyReport.md/cumulative.md
Labels: documentation

#58 Project manager
  README.pdf
  documents/Management/ManagementArtifacts/management_artifact.md
  documents/Management/weeklyReport.md/cumulative.md
  documents/Management/weeklyReport.md/weekly_report_6.md
Labels: documentation

#60 quick issue fixed
  documents/Management/weeklyReport.md/weekly_report_6.md
Labels: documentation

#59 Documents
  README.pdf
  documents/Management/ManagementArtifacts/management_artifact.md
  documents/Management/weeklyReport.md/cumulative.md
  documents/Management/weeklyReport.md/weekly_report_6.md
Labels: documentation
