Repository algosup/2024-2025-project-3-quickest-path-team-5, pull requests merged in 2025-01, with the labels that each got.

#1 init the document folder, should have been done before but I forgor
  documents/technical_specifications/TechnicalSpecifications.md
Labels: documentation, enhancement

#3 Documents
  documents/technical_specifications/TechnicalSpecifications.md
Labels: documentation, enhancement

#5 PR - Fix Issue on ReadME
  README.md
Labels: documentation

#7 Adding issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, enhancement

#10 Technical specifications
  documents/technical_specifications/CodingConventions.md
  documents/technical_specifications/TechnicalSpecifications.md
Labels: documentation

#13 Implement workflow + github issue template for documentation
  .github/ISSUE_TEMPLATE/documentation_issue.md
  .github/workflows/test-caller.yml
Labels: enhancement

#14 Data validation system via DGV
  .gitignore
  LICENSE.md
  README.md
  dag_graph_validator/CMakeLists.txt
  dag_graph_validator/src/data_struct/graphLib.c
  dag_graph_validator/src/data_struct/graphLib.h
  dag_graph_validator/src/dgv.c
  dag_graph_validator/src/io/csv_reader.c
  dag_graph_validator/src/io/csv_reader.h
  dag_graph_validator/src/io/mermaid_writer.c
  dag_graph_validator/src/io/mermaid_writter.h
  dag_graph_validator/test/test.cc
Labels: code

#15 Data validation
  dag_graph_validator/CMakeLists.txt
  dag_graph_validator/src/dgv.c
  dag_graph_validator/src/io/mermaid_writer.c
  dag_graph_validator/src/io/mermaid_writter.h
Labels: bug, enhancement

#25 Qa docs
  documents/QA/TestPlan.md
  documents/qa/TestCases.md
  documents/qa/TestPlan.md
Labels: documentation, enhancement

#24 Technical specifications
  documents/technical_specifications/APIDocumentation.md
  documents/technical_specifications/TechnicalSpecifications.md
  documents/technical_specifications/images/DuplicateEdge.png
  documents/technical_specifications/images/FibonacciHeap.png
Labels: documentation, enhancement

#26 Readme update
  README.md
Labels: documentation, enhancement

#27 Dijkstra algo implem + ALT one
  .gitignore
  api_interface/img/logo.png
  api_interface/index.html
  cap/CMakeLists.txt
  cap/src/api/Api.cpp
  cap/src/api/Api.hpp
  cap/src/cap.cpp
  cap/src/data_struct/edge.cpp
  cap/src/data_struct/edge.hpp
  cap/src/data_struct/graph.cpp
  cap/src/data_struct/graph.hpp
  cap/src/data_struct/node.cpp
  cap/src/data_struct/node.hpp
  cap/src/io/csv_reader.cpp
  cap/src/io/csv_reader.hpp
  cap/test/test.cc
  dag_graph_validator/CMakeLists.txt
  dag_graph_validator/src/dgv.c
  dag_graph_validator/src/io/graphviz_exporter.c
  dag_graph_validator/src/io/graphviz_exporter.h
Labels: enhancement, code
